// include standard libraries
#include <stdio.h>
#include <stdarg.h>
#include <string.h>
#include <cstdlib>
#include <string>
#include <sstream>
#include <vector>
#include <algorithm>
#include <map>
#include <iostream>
// apache and apr
#include "httpd.h"
#include "http_core.h"
#include "http_config.h"
#include "http_log.h"
#include "http_main.h"
#include "http_protocol.h"
#include "http_request.h"
#include "apr.h"
#include "apr_sha1.h"
#include "apr_global_mutex.h"
#include "apr_pools.h"
#include "apr_uri.h"
#include "apr_atomic.h"
#include "apr_base64.h"
#include "apr_buckets.h"
#include "apr_general.h"
#include "apr_time.h"
#include "ap_config.h"
#include "ap_mpm.h"
#include "apr_file_io.h"
#include "apr_strings.h"
#include "apr_hash.h"
#include "apr_tables.h"
#include "apr_lib.h"
#include "apr_dbd.h"
#include "apu_version.h"
#include "apr_xml.h"
#include "util_filter.h"
#include "util_script.h"
#include "util_cookies.h"
#include "util_xml.h"
// other libs
#include "scoreboard.h"
#include "odbtp.h"
#include "sqlite3.h"
#include "SimpleIni.h"
#include "json.h"
#include "ibpp/core/ibpp.h"
// boost
#include <boost/algorithm/string.hpp>