// chilkat defines
//#include "CkCert.h"
//#include "CkCertChain.h"
//#include "CkCertStore.h"
//#include "CkCertCollection.h"
#include "CkCrypt.h"
#include "CkCrypt2.h"
//#include "CkHttpRequest.h"
//#include "CkHttp.h"
//#include "CkHttpResponse.h"
//#include "CkString.h"
//#include "CkStringArray.h"
//#include "CkXml.h"
//#include "CkFileAccess.h"
//#include "CkFileList.h"
//#include "CkHtmlToXml.h"
// chilkat keys
#define KCKMail		"DILITHMAILQ_2vRHpYc49Q4x"
#define KCKZip		"DILITHZIP_JPL0kA301WsU"
#define KCKCrypt	"DILITHCrypt_5N5HtQmJNRKb"
#define KCKMht		"DILITHMHT_5ahLbkyS2EuG"
#define KCKMime		"DILITHSMIME_JGKTM3Ue3CpG"
#define KCKCharset	"DILITHCharset_HbHLQa8dRR4G"
#define KCKIMAP		"DILITHIMAPMAILQ_EhOMon543Q3E"
#define KCKBounce	"DILITHBOUNCE_t56CcHPQ9L7U"
#define KCKPFX		"DILITHPFX_YhUALuR24ZvK"
#define KCKFTP2		"DILITHFTP_PvtEu5BFlVnI"
#define KCKHTTP		"DILITHHttp_UoUJcWhRZR2K"
#define KCKHTTP2XML	"DILITHHtmlToXml_JF7fbV62ZE6j"
#define KCKXMP		"DILITHXMP_rk49KOHs3QxM"
#define KCKRSA		"DILITHRSA_6Rg6PqE97TnG"
#define KCKDSA		"DILITHDSA_4v4E65aQmBnY"
#define KCKSSH		"DILITHSSH_aJ2P7LcH9RnG"
#define KCKDH		"DILITHDiffie_XL0UzOptSRmG"
#define KCKCompress	"DILITHCompress_Vq4gk9fgYUmU"
#define KCKSocket	"DILITHSocket_VKguqgf7CK2G"
#define KCKTar		"DILITHTarArch_G7nANMpV3SIa"
